### ISSUE TITLE
InputConnector and OutputConnector must be typed

### ISSUE THREAD

**Issue by Highlife1911** [hpicgs/yats#38]
Both classes must be typed with the parameter type and have a common base class AbstractConnector. This issue has priority.

**Comment by mflueggen** [comment]
I began typing the classes Input- and OutputConnector. What type should the functions `input `and `output ` of `AbstractTaskConfigurator` return?

**Comment by Highlife1911** [comment]
`AbstractInputConnector` and `AbstarctOutputConnector`
