### ISSUE TITLE
Questions while creating a more complex example

### ISSUE THREAD

**Issue by mflueggen** [hpicgs/yats#74]
Hi Guys,
I wish you a Merry Christmas.

I am trying to create an example to demonstrate the usage of our pipeline. I want to count all the words in a text file and print the 10 most used words (this problem just calls for a pipeline).

To solve this problem, I want to create a pipeline consisting out of the following 5 tasks:

- Task 1 reads the file line by line and forwards the read line to task 2.
- Task 2 separates the line into words and forwards each individual word to task 3.
- Task 3 converts each letter in a word to uppercase and forwards the word consisting only out of uppercase letters to task 4.
- Task 4 saves and counts the words. Every n words it triggers Task 5.
- Task 5 prints the top 10 most used words to the console.

I am unsure to implement the following behavior using our framework/pattern:
When created, task 1 opens a text file. Task 1 "can_run", because the EOF of the file has not been reached and Task 2 can process the next line (how do I know this?). So, Task 1 reads the next line and writes it to its output. Task 1 cannot run anymore because there is data in its output. Task 2 can run now because there is data in its input. Task 2 takes the line and begins processing it. At that moment Task 1 should be runnable again because its output has been read (how do I know this?). Now Task 1 reads the next line and writes it to its output while Task 2 is still processing the first line while handing the individual words down to Task 3.

My concrete sticking points are:

1. Task 2 "can_run" if it is still processing a line or if a new line is waiting in its input. Which run method should the scheduler call (every run forwards an individual word to Task 3)?
2. How does the scheduler know that Task 2 has read the output of Task 1 so it can execute Task 1 again?

There exist implementations where there are buffers between the tasks which store the input and output values. For example:

Say, there was a buffer 1 between Task 1 and Task 2 and a buffer 2 after Task 2 for example. Both, Task 1 and Task 2 can access buffer 1 while Task 2 has additional access to buffer 2. If buffer 1 is empty, the scheduler can obviously run Task 1 which writes a new line to buffer 1. Task 2 can be run, if buffer 2 is empty and (there is data in buffer 1 or Task 2 is still processing a line). If task 2 wasn't processing a line it would fetch the next line from buffer 1 which would enable task 1 to be run again.

**Comment by Highlife1911** [comment]
This application does not work well with the current implementation. It is possible but not nice to implement using nested pipelines. The reason for this is that your idea wants to use features that are not implemented right now. Our scheduler currently only supports a run_once, so each task can only run once and not multiple times. Also our run function requires a parameter relation of 1:1, so each call consumes a constant amount of inputs and produces a constant amount of outputs. I would delay the implementation of the required features until the refactoring and the bug fixes are done.

For the simplicity of a first example please try to find something easy to implement using the currently available functions.

**Comment by mflueggen** [comment]
Please just keep this question in mind. As long as our pipeline  cannot be used for such kinds of problems we are missing the whole idea behind using the pipeline pattern and will fail the project.
