### ISSUE TITLE
Id collision?

### ISSUE THREAD

**Issue by mflueggen** [hpicgs/yats#94]
```
class blend_image_task
{
public:
	yats::output_bundle<yats::slot<std::string, "image"_id>>
		run(yats::slot<std::string, "filter1"_id> filter1, yats::slot<std::string, "filter2"_id> filter2)
	{
		return std::make_tuple(std::string("blended image"));
	}
};
```
does not compile because

> Can not add Task because multiple Inputs share the same Id.

However, if "filter2" is replaced by some random string it will compile just fine.

**Comment by Highlife1911** [comment]
Numbers are currently not supported by _id. It is possible to add support for them but this will reduce the maximum string length from 12 to 10.

**Comment by mflueggen** [comment]
Ah ok. We don't need numbers,

**Comment by Highlife1911** [comment]
I think we should support numbers. My idea is to change the maximum string length to 10. When the string length is 10 or less we store it like we do now. When the string is longer, than we store maybe the first 6 characters and hash the rest. SO we support longer names and numbers.

**Comment by Highlife1911** [comment]
this is by design
